### ISSUE TITLE
add json_serializable plugin

### ISSUE THREAD

**Issue by monkeyer** [fansvideo/fansvideo#20]

**Comment by monkeyer** [comment]
use 

```
dependencies:
   json_annotation:
   analyzer: '0.39.14'
dev_dependencies:
   json_serializable:
   build_runner:
```
